<div class="container-fluid h-100">

<div class="row">
    
  	<div class="col-md-6 pt-4 pl-5 pr-5">

  		<form action="/login" method="post">
			<div class="row">
				<div class="col">
					<input type="text" class="form-control" placeholder="E-mail" name="email">
				</div>
				<div class="col">
					<input type="password" class="form-control" placeholder="Senha" name="password">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-success mb-2">Entrar</button>
				</div>
			</div>
			
			<?php if($this->view->login == 'erro') { ?>

                <small class="form-text text-danger">
                    Login ou senha incorretos.
                </small>

            <?php } ?>

		</form>
	</div>
	</div>

</div>