<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/list">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logout">
	  		Sair
	  	</a>
			<img src="/img/gerenciarq_logo.jpeg" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-4">

			<div class="perfilPainel">
					
				<div class="row mt-2 mb-2">
					<div class="col mb-2">
						<span class="perfilPainelItem">Nome:</span><br />
						<span class="perfilPainelNome"><?php print_r($this->view->name['name']);?>Arquiteto X</span>
					</div>
				</div>
				<div class="row mb-2">

					<div class="col">
						<span class="perfilPainelItem">Tipode Acesso:</span><br />
						<span class="perfilPainelItemValor"><?php print_r($this->view->profile['total_tweet']);?>Profissional</span>
					</div>

				</div>
			</div>
		</div>
	

		<div class="col-md-8">
						</div-->
					<form action="/project" method="post">
						<div class="row">
							<div class="col">
								<input type="text" class="form-control" placeholder="Digit o nome do Projeto" name="project">
							</div>
							<div class="col-auto">
								<button type="submit" class="btn btn-secondary">Cadastrar novo projeto</button>
							</div>
						</div>
					</form>

			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?=$tweet['nome']; ?></strong> <small><span class="text text-muted">- <?=$tweet['data']; ?></span></small></p>
						<p><?=$tweet['tweet']; ?> </p>

						<?php if($tweet['id_usuarios'] == $_SESSION['id']) { ?>
							<form>
								<div class="col d-flex justify-content-end">
									<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-danger"><small>Remover</small></a>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>


			<div class="row tweet">
					<div class="col">
						<strong>Projeto 1</strong>
						<form>
							<div class="col d-flex justify-content-end">
								<a href="/action?action=excludeProject=<?=$project['id']?>" class="btn btn-danger"><small>Apagar</small></a>
							</div>
						</form>
					</div>
			</div>
			<div class="row tweet">
					<div class="col">
						<strong>Projeto 2</strong>
						<form>
							<div class="col d-flex justify-content-end">
								<a href="/action?action=excludeProject=<?=$project['id']?>" class="btn btn-danger"><small>Apagar</small></a>
							</div>
						</form>
					</div>
				</div>

		</div>

	</div>
</div>